version: "3.2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms750m -Xmx750m
    - xpack.security.enabled=false
    ports:
    - 9200:9200
